import { serialize } from 'next-mdx-remote/serialize';
import { MDXRemote } from 'next-mdx-remote';
import Head from 'next/head';

import Topic from '@/templates/Topic/Topic';
import BlogService from '@/services/BlogService';

import type { TopicProps } from '@/templates/Topic/Topic';
import type { GetServerSideProps, NextPage } from 'next';
import type { MDXRemoteSerializeResult } from 'next-mdx-remote';

type MDXProps = {
  mdxSource: MDXRemoteSerializeResult;
};

/* eslint-disable react/jsx-props-no-spreading */
const TopicPage: NextPage<TopicProps & MDXProps> = ({ topic, mdxSource }) => {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Topic topic={topic}>
        <MDXRemote {...mdxSource} />
      </Topic>
    </>
  );
};

export default TopicPage;

export const getServerSideProps: GetServerSideProps<MDXProps> = async context => {
  const slug = context.params?.slug as string;

  const mdxText = await BlogService.loadTopicMarkdown(slug);
  const mdxSource = await serialize(mdxText);

  const topic = await BlogService.loadTopic(slug);

  return {
    props: {
      mdxSource,
      topic,
    },
  };
};
