import Head from 'next/head';

import Blog from '@/templates/Blog/Blog';
import BlogService from '@/services/BlogService';

import type { GetServerSideProps, NextPage } from 'next';
import type { BlogProps } from '@/templates/Blog/Blog';

const BlogPage: NextPage<BlogProps> = ({ topics }) => {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Blog topics={topics} />
    </>
  );
};

export default BlogPage;

export const getServerSideProps: GetServerSideProps<BlogProps> = async () => {
  const topics = await BlogService.loadTopicPreviews();

  return {
    props: {
      topics,
    },
  };
};
